### ISSUE TITLE
Question: Why objectbox over hive?

### ISSUE THREAD

**Issue by Prn-Ice** [Katekko/ekko_app#4]

**Comment by Katekko** [comment]
I made my mind based on this article: https://objectbox.io/flutter-databases-sqflite-hive-objectbox-and-moor/

Plus, I found it easier then hive, because you can see how can I using. I create an interface to abstract the utilization of my DAO's, if you compare the old one (hive) and the new one (object box) you will see the second is very much clean then the first

**Comment by Prn-Ice** [comment]
Thanks for answering so quickly. I tried objectbox but I could not get it to use the Id from my API response as the table id, if I could fix that I'd be happy to use objectBox.

**Comment by Katekko** [comment]
> Thanks for answering so quickly. I tried objectbox but I could not get it to use the Id from my API response as the table id, if I could fix that I'd be happy to use objectBox.

You can think with me, when you are using some database to store data offline mostly you will need to create some objects, update others and whatever, all that offline, even if after you will call an api passing your data. 
To store your data locally you will need give a ID for the object that you are trying to save, so this is the box id, but you will need save your id from api, right, this is will be other attribute that you will save instead saving as ID.

Idk if I'm being transparency, but in my head is working for now lol
